[e5e0dc1b-0480-54bc-9374-aad01c23163d]
name = "Juno"
location = "https://docs.junolab.org/latest"
method = "hosted"

[1222c4b2-2114-5bfd-aeef-88e4692bbb3e]
name = "julia"
location = "https://docs.julialang.org"
method = "hosted"

[1c8ee90f-4401-5389-894e-7a04a3dc0f4d]
name = "IterableTables"
location = "https://www.queryverse.org/IterableTables.jl/stable/"
method = "hosted"

[dcc97b0b-8ce5-5539-9008-bb190f959ef6]
name = "GeoStats"
location = "https://juliaearth.github.io/GeoStats.jl/stable"
method = "hosted"

[112f6efa-9a02-5b7d-90c0-432ed331239a]
name = "VegaLite"
location = "https://www.queryverse.org/VegaLite.jl/stable/"
method = "hosted"

[ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a]
name = "Makie"
location = "https://makie.juliaplots.org/stable"
method = "hosted"

[c52e3926-4ff0-5f6e-af25-54175e0327b1]
name = "Atom"
location = "https://docs.junolab.org/latest"
method = "hosted"

[0987c9cc-fe09-11e8-30f0-b96dd679fdca]
name = "MonteCarloMeasurements"
location = "https://baggepinnen.github.io/MonteCarloMeasurements.jl/stable/"
method = "hosted"

[3e1990a7-5d81-5526-99ce-9ba3ff248f21]
name = "Hecke"
location = "https://thofma.github.io/Hecke.jl/latest/"
method = "hosted"

[91a5bcdd-55d7-5caf-9e0b-520d859cae80]
name = "Plots"
location = "http://docs.juliaplots.org/latest/"
method = "hosted"

[1a8c2f83-1ff3-5112-b086-8aa67b057ba1]
name = "Query"
location = "https://www.queryverse.org/Query.jl/stable/"
method = "hosted"

[587475ba-b771-5e3f-ad9e-33799f191a9c]
name = "Flux"
location = "https://fluxml.ai/Flux.jl/stable/"
method = "hosted"

[0c46a032-eb83-5123-abaf-570d42b7fbaa]
name = "DifferentialEquations"
location = "https://docs.sciml.ai/"
method = "hosted"

[4b11ee91-296f-5714-9832-002c20994614]
name = "Gaston"
location = "https://mbaz.github.io/Gaston.jl/stable/"
method = "hosted"

[b60c06c0-7e54-11e8-3788-4bd722d65317]
name = "CMBLensing"
location = "https://cosmicmar.com/CMBLensing.jl/stable/"
method = "hosted"

[a38d70fc-99f5-11e9-1e3d-cbca093024c3]
name = "Omniscape"
location = "https://docs.circuitscape.org/Omniscape.jl/stable/"
method = "hosted"

[ebb8d67c-85b4-416c-b05f-5f409e808f32]
name = "BSeries"
location = "https://ranocha.de/BSeries.jl/stable/"
method = "hosted"
