[e5e0dc1b-0480-54bc-9374-aad01c23163d]
name = "Juno"
location = "https://junolab.org/latest"
method = "hosted"

[112f6efa-9a02-5b7d-90c0-432ed331239a]
name = "VegaLite"
location = "https://www.queryverse.org/VegaLite.jl/stable/"
method = "hosted"

[1c8ee90f-4401-5389-894e-7a04a3dc0f4d]
name = "IterableTables"
location = "https://www.queryverse.org/IterableTables.jl/stable/"
method = "hosted"

[1a8c2f83-1ff3-5112-b086-8aa67b057ba1]
name = "Query"
location = "https://www.queryverse.org/Query.jl/stable/"
method = "hosted"

[c52e3926-4ff0-5f6e-af25-54175e0327b1]
name = "Atom"
location = "https://junolab.org/latest"
method = "hosted"
